module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct EmergencyState_ {
                boolean soft_emergency_triggered;   // 软紧急停止 (app触发)
                boolean hard_emergency_triggered;   // 硬紧急停止 (用户板触发)
                boolean amr_emergency_triggered;    // AMR紧急停止 (轮式底盘触发)
            };
        };
    };
};
