module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct IMUState_ {
                float quaternion[4];        // 四维四元数
                float gyroscope[3];         // 三维陀螺仪数据
                float accelerometer[3];     // 三维加速度计数据
                float rpy[3];               // 三维欧拉角（滚转、俯仰、偏航）
                uint8 temperature;          // 温度传感器数据
            };
        };
    };
};



