module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct LaserScan_ {
                uint64 timestamp;            // 时间戳（ms）
                int32 lidar[1024];          // 激光数据（最多1024点，未满补0）
            };
        };
    };
};


