#include "motor_cmd.idl"

module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct LowCmd_ {
                uint16 algs_mode;                  // 对算法状态机
                MotorCmd_ motor_cmd[30];           // 电机命令，包含 20 个 MotorCmd_ 结构体
            };
        };
    };
};

