#include "motor_cmd.idl"

module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct LowerCmd_ {
                MotorCmd_ motor_cmd[12];           // 电机命令，包含 12 个 MotorCmd_ 结构体
            };
        };
    };
};



