#include "imu_state.idl"
#include "motor_state.idl"
#include "bms_state.idl"

module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct LowerState_ {
                uint16 fsm_id;          /*对应算法状态机*/
                IMUState_ imu_state;
                MotorState_ motor_state[12];
                BmsState_ bms_state;
                octet wireless_remote[40];
                uint32 reserve;               /*越疆保留*/
            };
        };
    };
};


