module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct MotorCmd_ {
                uint8 mode;                        // 模式
                float q;                           // 位置
                float dq;                          // 速度
                float tau;                         // 力矩
                float kp;                          // 比例增益
                float kd;                          // 微分增益
            };
        };
    };
};



