module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct JoystickValue_ {
                float x;
                float y;    
            };

            @extensibility(FINAL)
            struct RemoteControl_ {
                JoystickValue_ btn_move;    // 左摇杆键值
                JoystickValue_ btn_turn;    // 右摇杆键值
            };
        };
    };
};

