module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct SetCalibrationFlag_ {
                boolean flag[13];
            };
        };
    };
};



