module dobot_atom{
    module msg{
        module dds_{
            @extensibility(FINAL)
            struct SwitchUpperControl_ {
                boolean flag;  /* true: 上肢有控制，false: 上肢无控制*/
            };
        };
    };
};




