module dobot_atom{
    module msg{
        module dds_{

            enum TeleopState {
                DISABLED,      // 禁用
                ENABLING,      // 正在启用
                ENABLED        // 启用
            };

            @extensibility(FINAL)
            struct TeleopStatus_ {
                TeleopState teleop_state;    // 遥操作状态
                TeleopState sync_state;      // 人机同步状态
                TeleopState record_state;    // 录制状态
            };
        };
    };
};
