
module dobot_atom{
    module msg{
        module dds_{
            enum TeleopCommandType {
                START_SYNC,          // 启动人机同步
                STOP_SYNC,           // 停止人机同步
                START_TELEOP,        // 启动遥操作
                STOP_TELEOP,         // 停止遥操作
                START_RECORD,        // 启动录制
                STOP_RECORD          // 停止录制
            };

            @extensibility(FINAL)
            struct TeleopCommand_ {
                TeleopCommandType command_type;    // 命令类型,参考上述TeleopCommandType
            };
        };

    };
};

